### PR TITLE
Update WeatherSymbol_WMO_PresentWeatherAutomaticStation_wawa_54.svg

### PR DESCRIPTION
**Pull request by hoborg5**
Hello! I've found mistake in symbol no. 54 icon. Previously icon have represented havy drizzle (description was correct - freezing drizzle). I've just slightly modified parameters from symbol no. 55 and pasted it to 54.

### CODE REVIEW

**Comment by chris-little** [comment]
@hoborg5 Thank you for spotting that error and creating the PR.

**Review by chris-little — APPROVED** [review]

**Comment by hoborg5** [comment]
Thank you!

**Comment by chris-little** [comment]
@tomkralidis The Weather Symbol build failed with a Python 3.6 not in cache problem

**Comment by tomkralidis** [comment]
FYI #45 is now merged and fixes the (unrelated) CI error.  Merging.  Thanks for the contribution @hoborg5!

**Pull request merged**
