### PR TITLE
Temporary fix for the calm wind symbol

### PR DESCRIPTION
**Pull request by RousseauLambertLP**
Temporary fix calm wind symbol by reducing the circle radius from 18 to 15, until all the symbols gets harmonized.

### CODE REVIEW

**Comment by chris-little** [comment]
But doesn’t this then need scaling to fit around the total cloud symbols?

A better fix, and more permanent, would be to make this symbol have a clipping box/extent of say, 60x60 rather than 55x55. See below.

Chris

**Comment by RousseauLambertLP** [comment]
Sure this would be better. 

I changed my file (calm wind symbol) to keep the same circle radius and only changed the size of the extent of the symbol to 65x65 (original size of the circle). 

Louis-Philippe Rousseau L.

**Comment by tomkralidis** [comment]
@chris-little looks good? Should I merge?

**Comment by chris-little** [comment]
@tomkralidis Just back from holiday. Lost track.I think the answer to your question is 'merge'. I was confused by L-P's 'same circle radius' - same as what?

**Pull request merged**
